### PR TITLE
backend: stop returning 400 on no referrer

### PR DESCRIPTION
**Pull request by ghost**
🤡

### CODE REVIEW

**Review by Synar — APPROVED** [review]
Lol

**Comment by Synar** [comment]
Good catch

**Comment by ghost** [comment]
> Good catch

Related to this extension https://addons.mozilla.org/en-US/firefox/addon/clearurls/ that just deletes the GET parameter on the bootstrapping request instead of making it empty thus provoking crashes again and again...

You know, the random bug we've been searching since the release ? That's it.

🤡

**Comment by Synar** [comment]
Great! 

But to be fully honest I never searched for it. '^^

**Pull request merged**
